<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-RVTGE37" name="Search Flight tickets in Chrome" tests="1" failures="1" timestamp="5 Dec 2019 09:56:37 GMT" time="53.193" errors="0">
  <testcase name="SearchTickets" time="32.482" classname="TestClass.ParallelTest_FlightTicketsSearch">
    <failure type="java.lang.AssertionError" message="Test case has been failed">
      <![CDATA[java.lang.AssertionError: Test case has been failed
	at TestClass.ParallelTest_FlightTicketsSearch.SearchTickets(ParallelTest_FlightTicketsSearch.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- SearchTickets -->
</testsuite> <!-- Search Flight tickets in Chrome -->
