<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="69547" started-at="2019-06-06T12:49:49Z" finished-at="2019-06-06T12:50:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="69547" started-at="2019-06-06T12:49:49Z" finished-at="2019-06-06T12:50:59Z">
      <class name="TestClass.FlightTicketsSearch">
        <test-method status="PASS" signature="InitializingExtenReports()[pri:0, instance:TestClass.FlightTicketsSearch@6f7fd0e6]" name="InitializingExtenReports" is-config="true" duration-ms="155" started-at="2019-06-06T18:19:49Z" finished-at="2019-06-06T18:19:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitializingExtenReports -->
        <test-method status="PASS" signature="OpenBrowser()[pri:0, instance:TestClass.FlightTicketsSearch@6f7fd0e6]" name="OpenBrowser" is-config="true" duration-ms="35773" started-at="2019-06-06T18:19:49Z" finished-at="2019-06-06T18:20:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenBrowser -->
        <test-method status="PASS" signature="CreateReport(java.lang.reflect.Method)[pri:0, instance:TestClass.FlightTicketsSearch@6f7fd0e6]" name="CreateReport" is-config="true" duration-ms="6" started-at="2019-06-06T18:20:25Z" finished-at="2019-06-06T18:20:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestClass.FlightTicketsSearch.SearchTickets()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateReport -->
        <test-method status="FAIL" signature="SearchTickets()[pri:0, instance:TestClass.FlightTicketsSearch@6f7fd0e6]" name="SearchTickets" duration-ms="32721" started-at="2019-06-06T18:20:25Z" finished-at="2019-06-06T18:20:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test case has been failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test case has been failed
	at org.testng.Assert.fail(Assert.java:94)
	at TestClass.FlightTicketsSearch.SearchTickets(FlightTicketsSearch.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchTickets -->
        <test-method status="PASS" signature="GetReportResult(org.testng.ITestResult)[pri:0, instance:TestClass.FlightTicketsSearch@6f7fd0e6]" name="GetReportResult" is-config="true" duration-ms="398" started-at="2019-06-06T18:20:58Z" finished-at="2019-06-06T18:20:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=SearchTickets status=FAILURE method=FlightTicketsSearch.SearchTickets()[pri:0, instance:TestClass.FlightTicketsSearch@6f7fd0e6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetReportResult -->
        <test-method status="PASS" signature="TearDownApplication()[pri:0, instance:TestClass.FlightTicketsSearch@6f7fd0e6]" name="TearDownApplication" is-config="true" duration-ms="634" started-at="2019-06-06T18:20:58Z" finished-at="2019-06-06T18:20:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDownApplication -->
        <test-method status="PASS" signature="FlushingExtentReports()[pri:0, instance:TestClass.FlightTicketsSearch@6f7fd0e6]" name="FlushingExtentReports" is-config="true" duration-ms="238" started-at="2019-06-06T18:20:59Z" finished-at="2019-06-06T18:20:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FlushingExtentReports -->
      </class> <!-- TestClass.FlightTicketsSearch -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
